### ISSUE TITLE
ArgumentError (A secret is required

### ISSUE THREAD

**Issue by zzDRT** [IBM-Bluemix/get-started-ruby#2]
rails server
=> Booting WEBrick
=> Rails 3.2.22.5 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2017-02-23 17:04:29] INFO  WEBrick 1.3.1
[2017-02-23 17:04:29] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin16]
[2017-02-23 17:04:29] INFO  WEBrick::HTTPServer#start: pid=91863 port=3000

Started GET "/" for 127.0.0.1 at 2017-02-23 17:04:46 -0500

ArgumentError (A secret is required to generate an integrity hash for cookie session data. Use config.secret_token = "some secret phrase of at least 30 characters"in config/initializers/secret_token.rb):
  actionpack (3.2.22.5) lib/action_dispatch/middleware/cookies.rb:319:in `ensure_secret_secure'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/cookies.rb:284:in `initialize'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/cookies.rb:231:in `new'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/cookies.rb:231:in `signed'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/session/cookie_store.rb:50:in `block in unpacked_cookie_data'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/session/abstract_store.rb:57:in `stale_session_check!'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/session/cookie_store.rb:48:in `unpacked_cookie_data'
  rack (1.4.7) lib/rack/session/cookie.rb:107:in `extract_session_id'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/session/abstract_store.rb:53:in `block in extract_session_id'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/session/abstract_store.rb:57:in `stale_session_check!'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/session/abstract_store.rb:53:in `extract_session_id'
  rack (1.4.7) lib/rack/session/abstract/id.rb:43:in `load_session_id!'
  rack (1.4.7) lib/rack/session/abstract/id.rb:32:in `[]'
  rack (1.4.7) lib/rack/session/abstract/id.rb:267:in `current_session_id'
  rack (1.4.7) lib/rack/session/abstract/id.rb:273:in `session_exists?'
  rack (1.4.7) lib/rack/session/abstract/id.rb:107:in `exists?'
  rack (1.4.7) lib/rack/session/abstract/id.rb:127:in `load_for_read!'
  rack (1.4.7) lib/rack/session/abstract/id.rb:64:in `has_key?'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/flash.rb:258:in `ensure in call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/flash.rb:259:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.22.5) lib/active_support/callbacks.rb:405:in `_run__104429115824293933__call__3512956603188711714__callbacks'
  activesupport (3.2.22.5) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22.5) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.22.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22.5) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22.5) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22.5) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22.5) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22.5) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22.5) lib/action_dispatch/middleware/static.rb:83:in `call'
  railties (3.2.22.5) lib/rails/engine.rb:484:in `call'
  railties (3.2.22.5) lib/rails/application.rb:231:in `call'
  rack (1.4.7) lib/rack/content_length.rb:14:in `call'
  railties (3.2.22.5) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.7) lib/rack/handler/webrick.rb:59:in `service'
  /Users/danat/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/danat/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/danat/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

  Rendered /Users/danat/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.9ms)
  Rendered /Users/danat/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (2.1ms)
  Rendered /Users/danat/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (24.7ms)

**Comment by zzDRT** [comment]
I download again  GetStartedRuby.  When I ran rails server I got these errors and the following when attempting to browse to localhost:3000

 ArgumentError

A secret is required to generate an integrity hash for cookie session data. Use config.secret_token = "some secret phrase of at least 30 characters"in config/initializers/secret_token.rb

Rails.root: /Users/danat/sandbox/get-started-ruby
